name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/vhosts/fluu/fluu-api
            git pull git@github.com:VijayKadiyam/fluu-api.git
            echo 'Deployment Done'
            
      - name: Post Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/vhosts/fluu/fluu-api
            git add .
            git commit -m "Latest commit"
            php artisan migrate
            php artisan config:clear
            php artisan cache:clear
            echo 'Post Deployment'
